name: ci

on: push
jobs:
  test:
    name: Rust test
    runs-on: ubuntu-latest
    steps:
      - name: "Test:checkout"
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Test:cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test